# Generated by Django 3.1.3 on 2020-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_category', '0002_auto_20201113_2118'),
        ('eshop_products', '0003_auto_20201105_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoris',
            field=models.ManyToManyField(blank=True, to='eshop_category.ProductsCaregory', verbose_name='دسته بندی ها'),
        ),
    ]
