# Generated by Django 3.1.3 on 2020-11-16 15:52

from django.db import migrations, models
import eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_auto_20201116_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=eshop_products.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
