# Generated by Django 3.1.3 on 2020-11-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر ها'},
        ),
    ]
