# Generated by Django 3.1.3 on 2020-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscaregory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterField(
            model_name='productscaregory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='productscaregory',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
    ]
