# Generated by Django 3.1.3 on 2020-11-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید کاربران'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'جزییات محصول', 'verbose_name_plural': 'اطلاعات جزییات محصولات'},
        ),
    ]
